export const GET_ALL_VIDEOGAMES="GET_ALL_VIDEOGAMES";
export const GET_VIDEOGAMES_BY_ID="GET_VIDEOGAMES_BY_ID"
export const REMOVE_DETAIL="REMOVE_DETAIL"
export const GET_VIDEOGAMES_BY_NAME="GET_VIDEOGAMES_BY_NAME"
export const FILTER="FILTER";
export const ORDENAR="ORDENAR";
export const GET_GENRES="GET_GENRES"


